#!/usr/bin/env node
require('dotenv').config({ path: '../../fleet.env' });
const BASE_URL = 'https://localhost:4443';

const body = {
    "config": {
        "delivery_policy": "latest",
        "prefer_typed": true,
        "port": 3000,
        "exp": 1704067200,
        "alert_types": [
            "service"
        ],
        "fields": {
            "`<field_to_stream>`": {
                "resend_interval_seconds": 3600,
                "minimum_delta": 1,
                "interval_seconds": 1800
            }
        },
        "ca": "-----BEGIN CERTIFICATE-----\ncert\n-----END CERTIFICATE-----\n",
        "hostname": "barnacle-pleasing-heavily.ngrok-free.app"
    },
    "vins": [
        `${process.env.TESLA_VEHICLE_ID}`,
    ]
}

const options = {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.TP_TOKEN}`
    }
};

fetch(`${BASE_URL}/api/1/vehicles/fleet_telemetry_config`, options)
    .then(res => res.json())
    .then(res => console.log(res))
    .catch(err => console.log('error', err));
