#!/usr/bin/env node
/* Sets the charge limit to the vehicle's standard charge limit (typically 80-90%). */

// Load environment variables from fleet.env
require('dotenv').config({ path: '../../fleet.env' });

const BASE_URL = 'https://fleet-api.prd.na.vn.cloud.tesla.com';
const vin = process.env.TESLA_VEHICLE_ID;

const body = {}

const options = {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.TP_TOKEN}`
    }
};

fetch(`${BASE_URL}/api/1/vehicles/${vin}/command/charge_standard`, options)
    .then(res => res.json())
    .then(res => console.log(res))
    .catch(err => console.log('error', err));
