#!/usr/bin/env node
/* Sends a GPS navigation request to the vehicle. */

// Load environment variables from fleet.env
require('dotenv').config({ path: '../../fleet.env' });

const BASE_URL = 'https://fleet-api.prd.na.vn.cloud.tesla.com';
const vin = process.env.TESLA_VEHICLE_ID;

const body = {
    "lat": 37.7749,
    "lon": -122.4194,
    "order": 1
}

const options = {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.TP_TOKEN}`
    }
};

fetch(`${BASE_URL}/api/1/vehicles/${vin}/command/navigation_gps_request`, options)
    .then(res => res.json())
    .then(res => console.log(res))
    .catch(err => console.log('error', err));
