#!/usr/bin/env node
/* Sets the scheduled departure time. */

// Load environment variables from fleet.env
require('dotenv').config({ path: '../../fleet.env' });

const BASE_URL = 'https://fleet-api.prd.na.vn.cloud.tesla.com';
const vin = process.env.TESLA_VEHICLE_ID;

const body = {
    "enable": true,
    "departure_time": 120,
    "off_peak_charging_enabled": false,
    "off_peak_charging_weekdays_only": true,
    "preconditioning_enabled": true,
    "end_off_peak_time": 120
}

const options = {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.TP_TOKEN}`
    }
};

fetch(`${BASE_URL}/api/1/vehicles/${vin}/command/set_scheduled_departure`, options)
    .then(res => res.json())
    .then(res => console.log(res))
    .catch(err => console.log('error', err));