services:
  db:
    image: postgres:17
    container_name: tesla_tokens_db
    environment:
      POSTGRES_DB: tesla_tokens_db
      POSTGRES_USER: rishabhmohapatra
      POSTGRES_PASSWORD: thebigflute2006
    ports:
      - "5433:5432"  # Changed host port to 5433, container still uses 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: tesla_fleet_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rishabhmohapatra:thebigflute2006@db:5432/tesla_tokens_db
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data: 