#!/usr/bin/env node
require('dotenv').config({ path: '../fleet.env' });
const BASE_URL = 'https://fleet-api.prd.na.vn.cloud.tesla.com';

const options = {
    method: 'GET',
    headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.PARTNER_TOKEN}`
    }
};

fetch(`${BASE_URL}/api/1/partner_accounts/public_key?domain=${process.env.NGROK_DOMAIN}`, options)
    .then(res => res.json())
    .then(res => console.log(res))
    .catch(err => console.log('error', err));
